import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const sampleGifts = [
  // ==========================================
  // Technology
  // ==========================================
  {
    title: "Temperature-Control Smart Mug",
    description: "App-controlled ceramic mug maintains coffee or tea at exact preferred temperature for 3 hours on single charge or all day on its charging coaster.",
    estimatedPrice: 2999,
    currency: "INR",
    category: "Technology",
    tags: ["tech", "coffee", "office", "desk", "smart", "gadgets", "practical"],
    vibe: "practical",
    detectiveClue: "The subject frequently reheats beverages, works demanding desk hours, and values functional everyday luxuries.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Noise-Cancelling Wireless Earbuds",
    description: "Active noise cancellation earbuds with transparency mode, 28-hour playtime, and IPX5 sweat resistance.",
    estimatedPrice: 3499,
    currency: "INR",
    category: "Technology",
    tags: ["tech", "audio", "music", "travel", "commute", "fitness", "focus"],
    vibe: "tech-savvy",
    detectiveClue: "Clues show a daily commuter or student who thrives in deep focus with music or podcasts.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "3-in-1 Foldable Magnetic Wireless Charging Station",
    description: "Compact MagSafe compatible folding dock charges smartphone, smartwatch, and earbuds simultaneously with neat cable management.",
    estimatedPrice: 1899,
    currency: "INR",
    category: "Technology",
    tags: ["tech", "gadgets", "organized", "minimalist", "desk", "travel"],
    vibe: "minimalist",
    detectiveClue: "The subject owns multiple gadgets and detests cluttered cables on their bedside table or work desk.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1622445262464-84b1456045b6?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Portable Bluetooth Thermal Label & Sticker Maker",
    description: "Pocket-sized inkless label printer with customizable fonts, border templates, and cute icon prints controlled from phone.",
    estimatedPrice: 1499,
    currency: "INR",
    category: "Technology",
    tags: ["tech", "cute", "stationery", "creative", "organized", "diy"],
    vibe: "cute",
    detectiveClue: "The subject loves organizing jars, notebooks, or craft projects and enjoys cute aesthetic tools.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },

  // ==========================================
  // Hobbies & Creative Arts
  // ==========================================
  {
    title: "Deluxe Acrylic & Watercolor Art Supplies Box",
    description: "Comprehensive 48-piece wooden artist case featuring artist-grade acrylic tubes, watercolors, mixing palette, brushes, and sketching pads.",
    estimatedPrice: 1499,
    currency: "INR",
    category: "Hobbies",
    tags: ["painting", "art", "creative", "diy", "drawing", "colorful", "purple"],
    vibe: "creative",
    detectiveClue: "The subject finds therapeutic joy in painting and loves hands-on creative expression.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Beginner Crochet & Amigurumi Crafting Kit",
    description: "Complete yarn kit with ergonomic hooks, stitch markers, safety eyes, and video tutorials to knit adorable plushies.",
    estimatedPrice: 899,
    currency: "INR",
    category: "Hobbies",
    tags: ["crochet", "craft", "diy", "cute", "creative", "knitting"],
    vibe: "cute",
    detectiveClue: "Subject enjoys cozy indoor pastimes and appreciates cute, handmade artisanal creations.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "DIY Botanical Candle Making Kit",
    description: "Natural soy wax flakes, dried floral petals, lavender and sandalwood essential oils, wicks, and vintage amber glass jars.",
    estimatedPrice: 1299,
    currency: "INR",
    category: "Hobbies",
    tags: ["diy", "candle", "craft", "home", "calm", "creative", "aroma"],
    vibe: "thoughtful",
    detectiveClue: "The subject loves cozy aromatherapy and takes pride in crafting personalized items for their living space.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Pottery & Clay Sculpting Starter Set",
    description: "Air-dry terracotta sculpting clay with 14 carving tools, smoothing sponges, waterproof sealer, and pastel acrylic paints.",
    estimatedPrice: 1199,
    currency: "INR",
    category: "Hobbies",
    tags: ["pottery", "clay", "art", "creative", "diy", "sculpture"],
    vibe: "creative",
    detectiveClue: "Investigation shows a creative spirit who enjoys tactile, screen-free weekend projects.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },

  // ==========================================
  // Personalized Gifts
  // ==========================================
  {
    title: "Custom Engraved Name Bar Pendant Necklace",
    description: "Hypoallergenic 18K gold-plated stainless steel bar engraved with a custom name or milestone date in delicate script font.",
    estimatedPrice: 1299,
    currency: "INR",
    category: "Personalized",
    tags: ["personalized", "jewelry", "sentimental", "cute", "fashion", "gold", "anniversary", "birthday"],
    vibe: "sentimental",
    detectiveClue: "The subject values sentimental tokens over mass-market goods, making custom engraving deeply touching.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Personalized Hardbound Leather Journal & Pen Set",
    description: "Full-grain vegan leather notebook debossed with recipient initials, 200 GSM fountain-pen friendly cotton paper, with brass rollerball pen.",
    estimatedPrice: 999,
    currency: "INR",
    category: "Personalized",
    tags: ["personalized", "writing", "journal", "stationery", "books", "thoughtful"],
    vibe: "thoughtful",
    detectiveClue: "A personalized journal appeals directly to someone who writes, reflects, or creates memories on paper.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Custom Illustrated Star Map Night Light",
    description: "Laser-engraved acrylic plate showing the exact constellation alignment from their special date and location with warm LED wooden base.",
    estimatedPrice: 1399,
    currency: "INR",
    category: "Personalized",
    tags: ["personalized", "sentimental", "anniversary", "birthday", "home", "romantic", "decor"],
    vibe: "sentimental",
    detectiveClue: "A commemorative keepsake capturing the night sky of their birthday or milestone anniversary.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Customized Spotify Song Plaque with Wooden Stand",
    description: "Clear acrylic music plaque displaying their favorite song title, artist, album art, and scannable code with personal message.",
    estimatedPrice: 799,
    currency: "INR",
    category: "Personalized",
    tags: ["personalized", "music", "cute", "sentimental", "decor", "friendship"],
    vibe: "cute",
    detectiveClue: "Music evokes deep emotional resonance; this physical emblem of their anthem shows thoughtful attention.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },

  // ==========================================
  // Books & Stationery
  // ==========================================
  {
    title: "Collector's Illustrated Boxset: Classic Literature",
    description: "Hardcover clothbound foil-stamped editions of timeless literature with silk ribbon markers and custom slipcase.",
    estimatedPrice: 2199,
    currency: "INR",
    category: "Books",
    tags: ["books", "reading", "literature", "classic", "introvert", "aesthetic"],
    vibe: "thoughtful",
    detectiveClue: "The subject enjoys quiet evenings reading and cherishes heirloom-grade physical editions.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Smart Ergonomic Reading Pillow with Neck Support",
    description: "Plush shredded memory foam bed rest lounger pillow with arm supports and side pockets for books and phone.",
    estimatedPrice: 1899,
    currency: "INR",
    category: "Books",
    tags: ["reading", "books", "cozy", "comfort", "home", "introvert"],
    vibe: "cozy",
    detectiveClue: "Subject spends hours engrossed in books or tablets in bed and values restorative comfort.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Vintage Japanese Fountain Pen & Shimmer Ink Set",
    description: "Fine nib brass-barrel fountain pen paired with three bottled inks including twilight purple and emerald shimmer.",
    estimatedPrice: 1599,
    currency: "INR",
    category: "Books",
    tags: ["stationery", "writing", "art", "purple", "calligraphy", "desk"],
    vibe: "thoughtful",
    detectiveClue: "Recipient takes pleasure in handwriting, journaling, and the elegance of vintage desk instruments.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },

  // ==========================================
  // Food & Gourmet Delights
  // ==========================================
  {
    title: "Artisanal Single-Origin Chocolate Tasting Trunk",
    description: "Assortment of 8 handcrafted dark and milk chocolate bars from artisanal Kerala and Idukki cacao estates with sea salt and roasted nuts.",
    estimatedPrice: 1199,
    currency: "INR",
    category: "Food",
    tags: ["food", "chocolate", "gourmet", "tasting", "sweet", "luxury"],
    vibe: "luxury",
    detectiveClue: "The subject has an appreciative palate for gourmet confections rather than mass-produced supermarket candy.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Estate Whole Bean Coffee Discovery Hamper",
    description: "Four 150g bags of specialty medium and dark roasts from Chikmagalur and Coorg estates with French Press measuring scoop.",
    estimatedPrice: 1399,
    currency: "INR",
    category: "Food",
    tags: ["coffee", "food", "drinks", "gourmet", "morning", "practical"],
    vibe: "practical",
    detectiveClue: "Clues point to a dedicated daily coffee drinker who takes ritualistic pride in fresh beans and distinct origins.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Exotic Herbal & Floral Loose Leaf Tea Vault",
    description: "Six pyramid tins with calming lavender chamomile, Kashmiri kahwa, blue pea flower, and Himalayan green tea with brass infuser.",
    estimatedPrice: 1099,
    currency: "INR",
    category: "Food",
    tags: ["tea", "calm", "wellness", "relaxation", "drinks", "healthy", "purple"],
    vibe: "calm",
    detectiveClue: "The subject values wellness rituals, mindfulness, and soothing caffeine-free evening beverages.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Italian Pasta Making & Gourmet Sauce Craft Box",
    description: "Wooden gnocchi board, brass ravioli wheel, 00 flour, aged balsamic glaze, and sun-dried tomato pesto seasoning.",
    estimatedPrice: 1699,
    currency: "INR",
    category: "Food",
    tags: ["cooking", "foodie", "diy", "dinner", "italian", "creative"],
    vibe: "fun",
    detectiveClue: "The subject enjoys entertaining or cooking authentic restaurant-quality dishes from scratch.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },

  // ==========================================
  // Fashion & Accessories
  // ==========================================
  {
    title: "Handcrafted Italian Leather Slim Bifold Wallet",
    description: "Full-grain genuine leather wallet with RFID-blocking sleeves, coin compartment, and slim pocket profile.",
    estimatedPrice: 1399,
    currency: "INR",
    category: "Fashion",
    tags: ["fashion", "leather", "wallet", "minimalist", "accessories", "practical"],
    vibe: "minimalist",
    detectiveClue: "A worn-out wallet is the most universally appreciated upgrade for someone who values sleek utility.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Pure Mulberry Silk Sleep Mask & Pillowcase Set",
    description: "Grade 6A 22-Momme natural silk pillowcase and matching eye mask that prevents hair frizz and skin creases.",
    estimatedPrice: 1999,
    currency: "INR",
    category: "Fashion",
    tags: ["beauty", "fashion", "sleep", "wellness", "luxury", "purple", "cozy"],
    vibe: "luxury",
    detectiveClue: "Investigation points to someone who treasures their sleep routine and enjoys indulgent bedtime self-care.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Minimalist Polarized Round Sunglasses with Bamboo Case",
    description: "UV400 polarized dark lenses with lightweight golden alloy frames and engraved cylindrical bamboo travel case.",
    estimatedPrice: 1199,
    currency: "INR",
    category: "Fashion",
    tags: ["fashion", "style", "accessories", "travel", "outdoor"],
    vibe: "stylish",
    detectiveClue: "A chic, versatile accessory suitable for someone who enjoys sunny getaways and effortless styling.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Boho Handwoven Macrame Sling Bag",
    description: "Eco-friendly cotton cord crossbody sling bag with fringed detailing, zip closure, and interior phone pocket.",
    estimatedPrice: 899,
    currency: "INR",
    category: "Fashion",
    tags: ["fashion", "cute", "boho", "aesthetic", "accessories", "style"],
    vibe: "cute",
    detectiveClue: "The subject loves aesthetic bohemian accents and relaxed weekend brunch outfits.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },

  // ==========================================
  // Beauty & Wellness
  // ==========================================
  {
    title: "Rose Quartz Facial Sculpting Gua Sha & Roller Set",
    description: "Authentic natural Brazilian rose quartz crystal roller with heart-shaped scraping tool in a magnetic gift box.",
    estimatedPrice: 999,
    currency: "INR",
    category: "Beauty",
    tags: ["beauty", "skincare", "wellness", "cute", "pink", "relaxation"],
    vibe: "cute",
    detectiveClue: "Subject takes pride in their skincare regimen and appreciates aesthetic self-care rituals.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Luxury Organic Bath & Spa Pamper Hamper",
    description: "French lavender body scrub, foaming bath salts, whipped shea butter lotion, and hand-poured soy relaxation candle.",
    estimatedPrice: 1799,
    currency: "INR",
    category: "Beauty",
    tags: ["beauty", "spa", "wellness", "relaxation", "calm", "lavender", "purple"],
    vibe: "thoughtful",
    detectiveClue: "The subject works hard and needs an explicit excuse to unwind and indulge in stress relief.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Compact Travel Essential Oil Ultrasonic Diffuser",
    description: "Whisper-quiet ceramic ultrasonic aroma mister with 7 ambient LED colors and automatic shut-off safety sensor.",
    estimatedPrice: 1299,
    currency: "INR",
    category: "Beauty",
    tags: ["wellness", "calm", "home", "aroma", "decor", "peaceful"],
    vibe: "calm",
    detectiveClue: "A soothing atmosphere builder that turns any bedroom or study into a peaceful sanctuary.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },

  // ==========================================
  // Home & Living
  // ==========================================
  {
    title: "Indoor Hydroponic Kitchen Herb Garden with Grow Light",
    description: "Self-watering smart planter with height-adjustable LED sunlight timer to grow fresh basil, mint, and oregano indoors.",
    estimatedPrice: 2499,
    currency: "INR",
    category: "Home",
    tags: ["home", "plants", "cooking", "gardening", "green", "smart", "tech"],
    vibe: "thoughtful",
    detectiveClue: "Subject enjoys gardening or cooking with fresh herbs but has limited outdoor garden space.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Hand-poured Amber & Sandalwood Ceramic Scented Candle",
    description: "Eco-friendly non-toxic soy wax candle with dual crackling wood wicks burning cleanly for 60 hours in ribbed ceramic bowl.",
    estimatedPrice: 799,
    currency: "INR",
    category: "Home",
    tags: ["home", "cozy", "decor", "candle", "calm", "relax"],
    vibe: "cozy",
    detectiveClue: "Ideal for someone who loves hosting, warm evening ambiances, and cozy aesthetics.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Nordic Minimalist Floating Ceramic Wall Planters",
    description: "Set of 3 geometric wall-hanging white and brass pots suitable for air plants, succulents, and trailing ivy.",
    estimatedPrice: 1199,
    currency: "INR",
    category: "Home",
    tags: ["home", "decor", "minimalist", "plants", "aesthetic", "living"],
    vibe: "minimalist",
    detectiveClue: "The subject has an eye for contemporary interior decor and loves infusing nature into their home.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Cozy Chunky Knit Fluffy Weighted Blanket",
    description: "Hand-knitted breathable cotton chunky blanket provides gentle soothing pressure without trapping excess heat.",
    estimatedPrice: 3299,
    currency: "INR",
    category: "Home",
    tags: ["home", "cozy", "sleep", "wellness", "warmth", "relaxation"],
    vibe: "cozy",
    detectiveClue: "Subject struggles with stress or loves cocooning on the couch with a good book on rainy evenings.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },

  // ==========================================
  // Gaming
  // ==========================================
  {
    title: "Retro RGB Mechanical Gaming Keyboard",
    description: "Hot-swappable mechanical switches with retro typewriter rounded keycaps, programmable macro shortcuts, and rainbow backlighting.",
    estimatedPrice: 2899,
    currency: "INR",
    category: "Gaming",
    tags: ["gaming", "tech", "keyboard", "desk", "fun", "rgb", "cool"],
    vibe: "fun",
    detectiveClue: "Subject logs serious hours gaming or coding and loves a visually expressive desk setup.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "RGB Edge-Lit Extended Gaming Mouse Pad with Wireless Charger",
    description: "XXL micro-textured water-resistant desk mat with 14 chroma lighting modes and built-in 15W phone charging pad.",
    estimatedPrice: 1299,
    currency: "INR",
    category: "Gaming",
    tags: ["gaming", "desk", "tech", "accessories", "rgb", "practical"],
    vibe: "fun",
    detectiveClue: "A high-utility, aesthetic addition to their gaming battlestation that keeps their mouse gliding smoothly.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Dual Wireless Gamepad Charging Station with LED Status",
    description: "Quick drop-in charging dock for PlayStation / Xbox controllers with fast 2.5 hour charging and smart overcharge protection.",
    estimatedPrice: 1199,
    currency: "INR",
    category: "Gaming",
    tags: ["gaming", "console", "playstation", "xbox", "tech", "organized"],
    vibe: "practical",
    detectiveClue: "Prevents the dreaded dead-controller frustration mid-game for console enthusiasts.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },

  // ==========================================
  // Fitness & Wellness
  // ==========================================
  {
    title: "Deep-Tissue Percussion Muscle Massage Gun",
    description: "Ultra-quiet brushless motor with 6 interchangeable massage heads, 20 speed levels, and 6-hour rechargeable battery.",
    estimatedPrice: 2299,
    currency: "INR",
    category: "Fitness",
    tags: ["fitness", "gym", "wellness", "recovery", "health", "practical"],
    vibe: "practical",
    detectiveClue: "Subject works out consistently, runs, or complains about tight shoulders from long desk sessions.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Eco-Friendly Cork Non-Slip Yoga Mat with Alignment Lines",
    description: "Natural organic cork and tree rubber yoga mat offering grip that strengthens with sweat, laser-etched posture guidelines.",
    estimatedPrice: 1699,
    currency: "INR",
    category: "Fitness",
    tags: ["fitness", "yoga", "wellness", "meditation", "eco", "healthy"],
    vibe: "calm",
    detectiveClue: "The subject prioritizes mindful movement, stretching, pilates, or daily morning sun salutations.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Insulated Motivational Stainless Steel Water Jug (1.5L)",
    description: "Triple-vacuum insulated thermal bottle keeps water ice cold for 24 hours with time markers and dual-sip lid.",
    estimatedPrice: 999,
    currency: "INR",
    category: "Fitness",
    tags: ["fitness", "health", "sports", "practical", "daily", "gym"],
    vibe: "practical",
    detectiveClue: "Hydration is essential; this rugged thermal bottle fits their active, on-the-move lifestyle.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },

  // ==========================================
  // Travel & Adventure
  // ==========================================
  {
    title: "Compressible Water-Resistant Packing Cubes Set (7 Pcs)",
    description: "Ultra-light ripstop nylon luggage organizers featuring double-zipper compression system and dedicated shoe bag.",
    estimatedPrice: 999,
    currency: "INR",
    category: "Travel",
    tags: ["travel", "organized", "vacation", "luggage", "practical", "adventure"],
    vibe: "practical",
    detectiveClue: "The subject catches flights often, takes weekend road trips, and appreciates neat packing systems.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1503220317375-aaad61436b1b?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "High-Capacity 20,000mAh Fast Charging Power Bank with Torch",
    description: "Airline-approved power bank charges laptops and phones simultaneously with 65W PD output and rugged shockproof shell.",
    estimatedPrice: 2199,
    currency: "INR",
    category: "Travel",
    tags: ["travel", "tech", "power", "gadgets", "outdoor", "practical"],
    vibe: "practical",
    detectiveClue: "Guarantees the subject stays connected on long flights, treks, or remote work escapades.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Scratch-off World & India Travel Map Poster",
    description: "Detailed matte black map revealing vibrant watercolor colors under gold foil as destinations are visited.",
    estimatedPrice: 799,
    currency: "INR",
    category: "Travel",
    tags: ["travel", "adventure", "decor", "fun", "wanderlust", "creative"],
    vibe: "fun",
    detectiveClue: "A proud visual record of past adventures that fuels future wanderlust and travel dreams.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },

  // ==========================================
  // Experiences & Sentimental Moments
  // ==========================================
  {
    title: "Fujifilm Instax Instant Photo Camera & Film Pack",
    description: "Retro instant camera with auto exposure, selfie mirror, and 20 credit-card sized instant film sheets.",
    estimatedPrice: 5999,
    currency: "INR",
    category: "Experiences",
    tags: ["photography", "memories", "creative", "cute", "camera", "sentimental", "purple"],
    vibe: "cute",
    detectiveClue: "The subject loves capturing spontaneous smiles, parties, and pinning real photos on their wall.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Curated Movie Night Popcorn & Treats Projection Box",
    description: "Mini popcorn popper with gourmet kernels, cheddar & caramel seasoning powders, and retro cinema cups.",
    estimatedPrice: 1299,
    currency: "INR",
    category: "Experiences",
    tags: ["fun", "movies", "food", "snacks", "cozy", "entertainment"],
    vibe: "fun",
    detectiveClue: "For film buffs who host cozy movie marathons and appreciate interactive evening snacks.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
  {
    title: "Couples & Friends 100 Date / Memory Scratch-off Poster",
    description: "Interactive bucket list poster featuring 100 unique bonding activities from stargazing to fondue nights.",
    estimatedPrice: 699,
    currency: "INR",
    category: "Experiences",
    tags: ["fun", "sentimental", "anniversary", "friendship", "activities", "cute"],
    vibe: "cute",
    detectiveClue: "Puts an end to 'What should we do tonight?' by providing interactive shared adventures.",
    affiliateUrl: "https://amazon.in",
    imageUrl: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600&auto=format&fit=crop&q=80",
    isCurated: true,
  },
];

async function main() {
  console.log(`Starting seed: inserting ${sampleGifts.length} curated Gift Detective items in INR...`);

  // Clear existing items if any or upsert
  for (const gift of sampleGifts) {
    const existing = await prisma.giftIdea.findFirst({
      where: { title: gift.title },
    });

    if (existing) {
      await prisma.giftIdea.update({
        where: { id: existing.id },
        data: gift,
      });
    } else {
      await prisma.giftIdea.create({
        data: gift,
      });
    }
  }

  const count = await prisma.giftIdea.count();
  console.log(`Seed completed successfully! Total gifts in catalog: ${count}`);
}

main()
  .catch((e) => {
    console.error("Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
